#!/usr/bin/python2
#coding=utf-8


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]


def keluar():
	print "\033[1;96m[!] \x1b[1;91mExit"
	os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(00000.1)



back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """

\033[1;97m        ___    ___   _   _ _____ _     
\033[1;92m       / _ \  / _ \ | | | |_   _| | Updated✔ 
\033[1;97m      / /_\ \/ /_\ \| |_| | | | | |    
\033[1;92m      |  _  ||  _  ||  _  | | | | |    
\033[1;97m      | | | || | | || | | |_| |_| |____
\033[1;97m      \_| |_/\_| |_/\_| |_/\___/\_____/
                                                               

"""



jalan("\033[1;96m•◈•   _____ _____  ______ ______ _____ _____ ")
jalan("\033[1;96m•◈•  / ____|  __ \|  ____|  ____|  __ \_   _|")
jalan("\033[1;97m•◈• | (___ | |__) | |__  | |__  | |  | || |  ")
jalan("\033[1;96m•◈•  \___ \|  ___/|  __| |  __| | |  | || |  ")
jalan("\033[1;96m•◈•  ____) | |    | |____| |____| |__| || |_ ")
jalan("\033[1;96m•◈• |_____/|_|    |______|______|_____/_____|")
 

jalan("   \037[1;93m Welcome to Internet Help Zone ")


CorrectUsername = "Internet"
CorrectPassword = "Subescribe"


loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;95m[☆] \x1b[1;92mUSER ID \x1b[1;36m>>>> ")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;94m[☆] \x1b[1;37mPASWORD \x1b[1;93m>>>> ")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username
            loop = 'false'
        else:
            print "Wrong Password"
            os.system('xdg-open https://www.youtube.com/channel/UCM4wF_X6IV4SNRumm4N_3IA')
    else:
        print "Wrong Username"
        os.system('xdg-open https://www.youtube.com/channel/UCM4wF_X6IV4SNRumm4N_3IA')

def login():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
		print logo
		print 50*"\033[1;96m▪"
		
		jalan("   \037[1;93m Run Tools \34[1;97m ") bash setup
		
		
